name: setup-node
description: "Setup Node.js âš™ï¸ - Cache dependencies âš¡ - Install dependencies ğŸ”§"
runs:
  using: "composite"
  steps:
    - name: Setup pnpm âš™ï¸
      uses: pnpm/action-setup@v2

    - name: Setup Node.js & Cache dependencies âš™ï¸
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"
        cache-dependency-path: "./pnpm-lock.yaml"

    - name: Install dependencies ğŸ”§
      shell: bash
      run: pnpm ci